name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check code
        run: cargo check

      - name: Format code
        run: cargo fmt -- --check

      - name: Lint code
        uses: actions-rs/clippy-check@v1

      - name: Audit dependencies
        run: cargo audit

      - name: Test code
        run: cargo test

      - name: Build project
        run: cargo build --verbose